apiVersion: v1
kind: Service
metadata:
  name: lab5
  namespace: {{ default "staging" .Release.Namespace }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: lab5
  type: ClusterIP