name: Build and push the latest build to staging

on:
  push:
    branches: [ main ]

jobs:
  build_push_image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3.0.0
      
      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push staging images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: ${{secrets.ACR_NAME}}/lab5:latest

  deploy:
    runs-on: ubuntu-20.04
    needs: build_push_image
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v2   

      - name: Helm tool installer
        uses: Azure/setup-helm@v4.2.0

      - name: Install Helm
        uses: Azure/setup-helm@v4
        with:
          version: v4.2.0

      - name: Sign in to Azure with OIDC
        uses: Azure/login@v2.1.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v4.0.0
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          cluster-name: ${{ secrets.CLUSTER_NAME }}

      - name: Run Helm Deploy
        run: |
          helm upgrade \
            --install \
            --create-namespace \
            --atomic \
            --wait \
            --namespace staging \
            lab5 \
            ./helm-lab5 \
            --set image.repository=${{ secrets.ACR_NAME }} \
            --set dns.name=${{ secrets.DNS_NAME }}

            
            
            
